services:
  django:
    image: sound-api
    container_name: sound-api
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    env_file: .environment
    ports:
      - "5000:5000"
    volumes:
      - .:/src

  postgres-main:
    image: postgres:14
    container_name: sound-postgres-main
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres-main:/var/lib/postgresql/data
    env_file: .environment

  minio:
    image: minio/minio
    container_name: sound-minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: .environment
    volumes:
      - ./storage/minio:/data

networks:
  default:
    name: sound